# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - label: Extensions
    link: /packages?packagist_type=bolt-extension
  - label: Themes
    link: /packages?packagist_type=bolt-theme
  - label: Bolt
    link: https://boltcms.io
    class: bolt-site
